// Mock data for The Respite â€” a Drawsteel TTRPG companion
// Drawsteel uses: Might/Agility/Reason/Intuition/Presence, Stamina, Recoveries, Heroic Resources

const PLAYERS = [
  {
    id: "gm",
    name: "Aldric",
    handle: "@aldric",
    role: "Director",
    avatar: "ember",
    initials: "A",
    pronouns: "he/him",
    joined: "2024-11-02",
  },
  {
    id: "p1",
    name: "Mira",
    handle: "@mira",
    role: "Player",
    avatar: "moss",
    initials: "M",
    pronouns: "she/her",
    joined: "2024-11-02",
  },
  {
    id: "p2",
    name: "Caspian",
    handle: "@cas",
    role: "Player",
    avatar: "arcane",
    initials: "C",
    pronouns: "he/him",
    joined: "2024-11-02",
  },
  {
    id: "p3",
    name: "Wren",
    handle: "@wren",
    role: "Player",
    avatar: "gold",
    initials: "W",
    pronouns: "they/them",
    joined: "2024-11-15",
  },
  {
    id: "p4",
    name: "Tova",
    handle: "@tova",
    role: "Player",
    avatar: "blood",
    initials: "T",
    pronouns: "she/her",
    joined: "2024-12-08",
  },
];

const CHARACTERS = {
  p1: {
    ownerId: "p1",
    name: "Sable Vex",
    pronouns: "she/her",
    ancestry: "Revenant",
    career: "Bounty Hunter",
    careerData: {
      benefits: "Start with one Renown and one favor owed by a local guard captain. +2 Project Points per downtime.",
      skills: ["Track", "Intimidate"],
      perk: "Marked Quarry â€” once per session, declare an enemy your bounty; gain edge on attacks against them.",
      incident: "The hunt that went wrong. A name you don't say aloud.",
    },
    culture: {
      languages: ["Caelian", "Khoursir cant", "Old Tongue (read only)"],
      environment: "Urban â€” fog-cities, wet stone, lamplight",
      organization: "Anarchic â€” the Eighth Hour answers to none",
      upbringing: "Underclass â€” raised in the cinder-warrens",
      complications: ["The Sablecut sings when blood is near", "Sunlight makes her skin itch"],
    },
    cls: "Shadow",
    kit: "Stickybomb",
    level: 4,
    xp: { current: 38, next: 60 },
    victories: 11,
    surges: 2,
    portrait: "shadow-blade portrait",
    portraitTint: "moss",
    titles: ["The Quiet Knife", "Of the Eighth Hour"],
    stamina: { current: 38, max: 52, recoveries: { current: 6, max: 8, value: 17 } },
    resource: { name: "Insight", current: 4, max: 7 },
    characteristics: {
      Might: 1, Agility: 3, Reason: 2, Intuition: 2, Presence: 0,
    },
    abilities: [
      { tier: "Signature", name: "Twin Fang", type: "Action", keywords: "Melee, Weapon", text: "Two strikes against one or two creatures within reach. âŠ• Roll: Tier 1 â€” 2 dmg. Tier 2 â€” 5 dmg. Tier 3 â€” 8 dmg + bleeding (EoT).", potency: { stat: "Agility", weak: 1, average: 2, strong: 3 } },
      { tier: "Heroic", name: "Caltrops of the Eighth Hour", type: "Maneuver", cost: "3 Insight", keywords: "Area, Burst 2", text: "Each enemy in a burst takes 4 damage and is slowed (save ends). You may shift 1.", potency: { stat: "Agility", weak: 1, average: 2, strong: 3 } },
      { tier: "Heroic", name: "Vanish", type: "Maneuver", cost: "5 Insight", keywords: "Stealth", text: "Become hidden until end of next turn, even while observed. First attack from hidden gains edge." },
      { tier: "Triggered", name: "Cut & Run", type: "Triggered", trigger: "An enemy ends its turn adjacent.", keywords: "Movement", text: "Shift up to your speed. If you end adjacent to a different enemy, deal 1d6+Agility damage.", potency: { stat: "Agility", weak: 1, average: 2, strong: 3 } },
    ],
    features: [
      { name: "Shadow Step", text: "Once per turn, when you move, you may teleport up to 3 squares instead." },
      { name: "Stickybomb Kit", text: "Each combat begins with three alchemical stickbombs. Throw as a maneuver â€” 4 fire damage, square is difficult terrain until EoE." },
      { name: "Echo of the Mourning Bell", text: "When you fall to 0 stamina, the next attack against you misses. (Once per session.)" },
    ],
    inventory: [
      { name: "Twin shortswords (Sablecut)", note: "Reforged from a knight's broken longsword." },
      { name: "Hooded greatcloak, ash-grey", note: "" },
      { name: "Tinderbox & 8 stickbombs", note: "" },
      { name: "Locket â€” empty", note: "Was once a portrait. Cannot remember whose." },
      { name: "73 silver marks", note: "" },
    ],
    ties: [
      { who: "Brann Hollowfast", how: "Mentor (deceased)", note: "Owes him a final mercy. Has not yet delivered it." },
      { who: "Caspian", how: "Trust, reluctant", note: "Saved her life in the Underway. She does not like being indebted." },
      { who: "The Cinderwake Cartel", how: "Hunted by", note: "They have her name on a slate." },
    ],
    backstory: "Died once, on the steps of the cathedral, on the eighth hour of the eighth night. Came back wrong. The bell still rings in her chest when she sleeps.",
    goals: ["Find out who she was before the bell.", "Burn down the Cinderwake counting house.", "Stop flinching at warm hands."],
    conditions: [
      { name: "Bleeding (1)", source: "Marrowmaw bite", duration: "EoNT" },
    ],
    notes: "Refuses to drink wine. Will not say why.",
    weaknesses: [{ type: "Holy", value: 2 }],
    immunities: [{ type: "Necrotic", value: 5 }],
    wealth: 3,
    renown: 2,
    tempStamina: 4,
    heroTokens: 2,
    turnTaken: false,
    skills: [
      { name: "Sneak", group: "Intrigue", edge: true },
      { name: "Alertness", group: "Intrigue", edge: false },
      { name: "Climb", group: "Exploration", edge: false },
      { name: "Streetwise", group: "Lore", edge: true },
    ],
    perks: [
      { name: "Eighth Hour Resolve", text: "Edge on saves vs frightened." },
      { name: "Cinder-marked", text: "You always know which way is north." },
    ],
    projects: [
      { name: "Reforge the Sablecut", goal: 30, progress: 18, characteristic: "Reason" },
      { name: "Investigate the locket", goal: 20, progress: 5, characteristic: "Intuition" },
    ],
  },
  p2: {
    ownerId: "p2",
    name: "Vael Ostrim",
    pronouns: "he/him",
    ancestry: "Human (Khoursir)",
    career: "Sage",
    careerData: {
      benefits: "Start with a personal library worth 50gp. +1 Wealth from a stipend. Edge on Lore tests in any city with a temple.",
      skills: ["Research", "Decipher"],
      perk: "Folded Page â€” once per session, declare you have read about this; the Director answers one factual question.",
      incident: "You read a book you should not have. The page is still in your pocket.",
    },
    culture: {
      languages: ["Caelian", "Khoursir", "High Litany", "Two dead tongues"],
      environment: "Urban â€” universities, archives, scriptoria",
      organization: "Hierarchical â€” the Brotherhood of the Folded Page",
      upbringing: "Cloistered â€” raised among scholars",
      complications: ["The page in your pocket whispers in dreams", "You owe a debt of three favors to your old master"],
    },
    cls: "Talent",
    kit: "Cloak",
    level: 4,
    xp: { current: 41, next: 60 },
    victories: 14,
    surges: 1,
    portrait: "scholar in storm-grey robes",
    portraitTint: "arcane",
    titles: ["Of the Glassmoor AthenÃ¦um", "Reader of the Folded Page"],
    stamina: { current: 22, max: 34, recoveries: { current: 5, max: 6, value: 11 } },
    resource: { name: "Clarity", current: 6, max: 9 },
    characteristics: {
      Might: 0, Agility: 1, Reason: 3, Intuition: 2, Presence: 2,
    },
    abilities: [
      { tier: "Signature", name: "Lash of Thought", type: "Action", keywords: "Ranged 10, Psionic", potency: { stat: "Reason", weak: 1, average: 2, strong: 3 }, text: "Mind-spear at one target. Tier 1 â€” 3 psychic. Tier 2 â€” 6 psychic + slide 1. Tier 3 â€” 9 psychic + dazed (EoT)." },
      { tier: "Heroic", name: "Citadel of the Folded Page", type: "Maneuver", cost: "4 Clarity", keywords: "Aura 3", potency: { stat: "Reason", weak: 1, average: 2, strong: 3 }, text: "Allies in aura gain +2 to resist forced movement and have edge on Reason tests." },
      { tier: "Heroic", name: "Quiet the Storm", type: "Action", cost: "7 Clarity", keywords: "Area, Burst 3", text: "Each creature in burst is calmed â€” saves vs frightened, restrained, taunted end. Allies regain 1 recovery worth of stamina." },
      { tier: "Triggered", name: "Mark the Memory", type: "Triggered", trigger: "An enemy uses an ability.", keywords: "Reaction", text: "You memorize the ability. Once before next short rest, you may use it as if it were yours." },
    ],
    features: [
      { name: "Cloak Kit", text: "Robes of muted argent. While unarmored, +2 stamina max and disengage as a free action." },
      { name: "Reader of Folded Pages", text: "Once per session, ask the Director one question about an object's history. They must answer truthfully." },
    ],
    inventory: [
      { name: "Stormglass focus", note: "Hums when lightning is within a mile." },
      { name: "Field journal, half-full", note: "" },
      { name: "Letter from his sister, unopened", note: "Six months in his pocket." },
      { name: "Vial of moonsalt", note: "" },
    ],
    ties: [
      { who: "Sable Vex", how: "Allyship", note: "She is the most interesting problem he has met." },
      { who: "Master Halvern", how: "Estranged tutor", note: "Last words: 'Don't follow me.'" },
    ],
    backstory: "Walked away from the AthenÃ¦um after they classified his sister's death as 'incidental research loss.' Has been looking for the right page ever since.",
    goals: ["Find Halvern.", "Translate the page he stole.", "Not become his teacher."],
    conditions: [],
    notes: "Doesn't sleep with the lamp out.",
    weaknesses: [{ type: "Psychic", value: 3 }],
    immunities: [],
    wealth: 4,
    renown: 3,
    tempStamina: 0,
    heroTokens: 1,
    turnTaken: true,
    skills: [
      { name: "Magic", group: "Lore", edge: true },
      { name: "History", group: "Lore", edge: true },
      { name: "Insight", group: "Interpersonal", edge: false },
    ],
    perks: [
      { name: "Folded Page", text: "Once per session, ask the Director one question about an object." },
    ],
    projects: [
      { name: "Translate the stolen page", goal: 40, progress: 22, characteristic: "Reason" },
    ],
  },
  p3: {
    ownerId: "p3",
    name: "Bramble Underhowe",
    pronouns: "they/them",
    ancestry: "Polder",
    career: "Wise One",
    careerData: {
      benefits: "Locals offer hearth and bread without coin. Edge on Heal tests outside settlements.",
      skills: ["Heal", "Nature"],
      perk: "Stillwater Vow â€” your spoken word stops violence for one round, once per session. Cannot be broken.",
      incident: "The grove you tend is dying. You don't know why.",
    },
    culture: {
      languages: ["Caelian", "Sylvan murmur", "Sign of the Hollow"],
      environment: "Wilderness â€” the Hollow Reach, the moss-line",
      organization: "Communal â€” kin-circles, no ranks",
      upbringing: "Pastoral â€” raised by hearth and herb",
      complications: ["Cannot lie. Ever.", "A knot of holly grows from the wound that killed your sibling"],
    },
    cls: "Conduit",
    kit: "Mountain",
    level: 4,
    xp: { current: 35, next: 60 },
    victories: 8,
    surges: 3,
    portrait: "polder cleric, oak charm",
    portraitTint: "gold",
    titles: ["Hand of the Stillwater Grove"],
    stamina: { current: 41, max: 48, recoveries: { current: 7, max: 8, value: 16 } },
    resource: { name: "Piety", current: 5, max: 6 },
    characteristics: {
      Might: 2, Agility: 0, Reason: 1, Intuition: 3, Presence: 2,
    },
    abilities: [
      { tier: "Signature", name: "Sanctified Strike", type: "Action", keywords: "Melee, Weapon, Holy", potency: { stat: "Intuition", weak: 1, average: 2, strong: 3 }, text: "Tier 1 â€” 3 dmg. Tier 2 â€” 6 dmg + ally within 5 regains 1d6 stamina. Tier 3 â€” 9 dmg + bright light EoT." },
      { tier: "Heroic", name: "Hands That Do Not Falter", type: "Action", cost: "3 Piety", keywords: "Ranged 5, Healing", text: "An ally spends a recovery and adds +Intuition." },
      { tier: "Heroic", name: "The Grove Endures", type: "Maneuver", cost: "5 Piety", keywords: "Aura 2", text: "Allies in aura have +2 stamina temporary at the start of each of their turns until EoE." },
    ],
    features: [
      { name: "Mountain Kit", text: "Heavy plate. -1 speed, +6 stamina max, +1 to stability checks." },
      { name: "Stillwater Vow", text: "Cannot tell a knowing lie. In return: once per session, your word stops violence for one round." },
    ],
    inventory: [
      { name: "Oaken war-hammer 'Quiet'", note: "Carved with the names of the saved." },
      { name: "Reliquary of the Stillwater", note: "" },
      { name: "Pouch of dried thyme & bread", note: "" },
    ],
    ties: [
      { who: "The Grove", how: "Sworn", note: "" },
      { who: "Tova", how: "Found-family", note: "Met on the road. Refuses to leave her behind." },
    ],
    backstory: "Walked out of the grove with a hammer and a promise. Has not yet broken either.",
    goals: ["Bring the lost back to the Stillwater.", "Forgive Tova for what she did at Greysend.", "Eat a proper meal."],
    conditions: [
      { name: "Blessed (+1 to first roll)", source: "Morning rite", duration: "Until used" },
    ],
    notes: "Sings while cooking. Badly.",
    weaknesses: [],
    immunities: [{ type: "Poison", value: 5 }, { type: "Corruption", value: 3 }],
    wealth: 2,
    renown: 4,
    tempStamina: 6,
    heroTokens: 3,
    turnTaken: false,
    skills: [
      { name: "Heal", group: "Crafting", edge: true },
      { name: "Nature", group: "Exploration", edge: false },
      { name: "Persuade", group: "Interpersonal", edge: false },
    ],
    perks: [
      { name: "Stillwater Vow", text: "Cannot lie. In return: your word stops violence for one round, once per session." },
    ],
    projects: [
      { name: "Build a roadside shrine", goal: 25, progress: 11, characteristic: "Might" },
    ],
  },
  p4: {
    ownerId: "p4",
    name: "Iskra Vail",
    pronouns: "she/her",
    ancestry: "Devil",
    career: "Soldier",
    careerData: {
      benefits: "Field commission. +1 Renown among veterans. Begin with a signed pardon for one past crime.",
      skills: ["Strategy", "Endurance"],
      perk: "Lieutenant's Eye â€” once per encounter, name an enemy; allies have edge against it until your next turn.",
      incident: "The Tenth Cohort burned. You walked out. The records say otherwise.",
    },
    culture: {
      languages: ["Caelian", "Infernal", "Field-cant"],
      environment: "Urban & wilderness â€” wherever the cohort is sent",
      organization: "Hierarchical â€” the Reformed Cohorts (former)",
      upbringing: "Martial â€” raised in barracks, drilled in steel",
      complications: ["Your pardon expires in one year", "Cinderbar grows hot when you lie"],
    },
    cls: "Tactician",
    kit: "Panoply",
    level: 4,
    xp: { current: 39, next: 60 },
    victories: 17,
    surges: 0,
    portrait: "horned soldier, scarred jaw",
    portraitTint: "blood",
    titles: ["Lieutenant of the Black Spire (former)"],
    stamina: { current: 30, max: 56, recoveries: { current: 4, max: 8, value: 18 } },
    resource: { name: "Focus", current: 3, max: 7 },
    characteristics: {
      Might: 3, Agility: 2, Reason: 1, Intuition: 1, Presence: 0,
    },
    abilities: [
      { tier: "Signature", name: "Cleaving Order", type: "Action", keywords: "Melee, Weapon", potency: { stat: "Might", weak: 2, average: 3, strong: 4 }, text: "Strike one creature, then an ally within 5 may make a free strike. Tier 1 â€” 3. Tier 2 â€” 6 + slow. Tier 3 â€” 9 + prone." },
      { tier: "Heroic", name: "Hold the Line", type: "Maneuver", cost: "4 Focus", keywords: "Aura 2", potency: { stat: "Might", weak: 2, average: 3, strong: 4 }, text: "Allies in aura gain +2 to all defenses until start of your next turn." },
      { tier: "Heroic", name: "On My Mark", type: "Triggered", cost: "6 Focus", trigger: "An ally rolls a tier 1.", keywords: "Reaction", text: "They reroll. Use the new result." },
    ],
    features: [
      { name: "Panoply Kit", text: "Full plate, tower shield. -2 speed, +8 stamina max, +1 to all defenses while shield is held." },
      { name: "Lieutenant's Eye", text: "Once per encounter, name an enemy. Allies have edge on attacks against it until EoE." },
    ],
    inventory: [
      { name: "Greatsword 'Cinderbar'", note: "Notched. She keeps the notches." },
      { name: "Tower shield, repainted black over crimson", note: "" },
      { name: "Stack of orders, never delivered", note: "" },
    ],
    ties: [
      { who: "Bramble", how: "Found-family", note: "Bramble is the one who pulled her out of Greysend." },
      { who: "The Black Spire", how: "Hunted by, hunts back", note: "" },
    ],
    backstory: "Followed orders for thirty years. Then she didn't. Greysend burned anyway.",
    goals: ["Make sure the next order is hers.", "Find the records of the Tenth Cohort.", "Apologize to Bramble. Eventually."],
    conditions: [
      { name: "Wounded", source: "Fell to 0 last session", duration: "Until full rest" },
    ],
    notes: "Will not sit with her back to a door.",
    weaknesses: [{ type: "Cold", value: 5 }],
    immunities: [{ type: "Fire", value: 5 }],
    wealth: 5,
    renown: 5,
    tempStamina: 0,
    heroTokens: 0,
    turnTaken: false,
    skills: [
      { name: "Intimidate", group: "Interpersonal", edge: true },
      { name: "Strategy", group: "Lore", edge: true },
      { name: "Endurance", group: "Exploration", edge: false },
    ],
    perks: [
      { name: "Lieutenant's Eye", text: "Once per encounter, name an enemy. Allies have edge against it." },
    ],
    projects: [
      { name: "Find the Tenth Cohort records", goal: 35, progress: 9, characteristic: "Presence" },
      { name: "Repair Cinderbar", goal: 15, progress: 12, characteristic: "Might" },
    ],
  },
};

const SESSIONS = [
  {
    id: "s14",
    number: 14,
    title: "The Hollow Beneath Greysend",
    date: "2026-06-14T19:00:00",
    location: "Aldric's place + Discord",
    mode: "hybrid",
    rsvps: { gm: "yes", p1: "yes", p2: "yes", p3: "maybe", p4: "yes" },
    summary: "Confront whatever has been pulling lights down the well. The Cinderwake ledger fragment points here.",
    upcoming: true,
  },
  {
    id: "s15",
    number: 15,
    title: "Wakeknight's Court",
    date: "2026-06-28T19:00:00",
    location: "Discord only â€” Aldric out of town",
    mode: "remote",
    rsvps: { gm: "yes", p1: "yes", p2: "yes", p3: "yes", p4: "no" },
    summary: "An audience with the masked judge. Bring a gift, or a confession.",
    upcoming: true,
  },
  {
    id: "s13",
    number: 13,
    title: "The Eighth Hour Bell",
    date: "2026-04-25T19:00:00",
    location: "Aldric's place",
    mode: "in-person",
    rsvps: { gm: "yes", p1: "yes", p2: "yes", p3: "yes", p4: "yes" },
    summary: "Sable heard the bell from her own chest. Vael bottled the sound. The ferryman is owed a name.",
    recap: "We met the ferryman. He took a name from each of us â€” but not the one he was supposed to. Caspian gave him 'Halvern' instead of his own. We do not yet know what this costs.",
    past: true,
  },
  {
    id: "s12",
    number: 12,
    title: "Greysend Burns",
    date: "2026-04-11T19:00:00",
    location: "Aldric's place",
    mode: "in-person",
    rsvps: { gm: "yes", p1: "yes", p2: "yes", p3: "yes", p4: "yes" },
    summary: "Iskra's old cohort came for the village. We were not enough.",
    recap: "Iskra fell to 0 holding the bridge. Bramble pulled her out. The village did not survive. None of us are okay.",
    past: true,
  },
  {
    id: "s11",
    number: 11,
    title: "The Folded Page",
    date: "2026-03-28T19:00:00",
    location: "Park cafÃ© (rained out â†’ moved to Mira's)",
    mode: "in-person",
    rsvps: { gm: "yes", p1: "yes", p2: "yes", p3: "no", p4: "yes" },
    summary: "Vael read the page he stole. He has not been the same since.",
    recap: "We learned three things. We can only say one of them aloud.",
    past: true,
  },
  {
    id: "s10",
    number: 10,
    title: "The Underway",
    date: "2026-03-14T19:00:00",
    location: "Aldric's place",
    mode: "in-person",
    rsvps: { gm: "yes", p1: "yes", p2: "yes", p3: "yes", p4: "yes" },
    summary: "First descent. Sable nearly didn't come back up.",
    recap: "Caspian carried her home. They have not spoken about it since.",
    past: true,
  },
];

const MEDIA = [
  { id: "m1", kind: "image", title: "Greysend, before", folder: "Maps", uploader: "gm", date: "2026-04-04", tags: ["map", "village"], placeholder: "village map Â· greysend" },
  { id: "m2", kind: "image", title: "The Underway, level 1", folder: "Maps", uploader: "gm", date: "2026-03-12", tags: ["map", "dungeon"], placeholder: "dungeon map Â· underway L1" },
  { id: "m3", kind: "image", title: "Sable Vex (commission)", folder: "Character art", uploader: "p1", date: "2026-02-19", tags: ["portrait", "sable"], placeholder: "portrait Â· sable vex" },
  { id: "m4", kind: "image", title: "Vael at the AthenÃ¦um", folder: "Character art", uploader: "p2", date: "2026-03-02", tags: ["portrait", "vael"], placeholder: "portrait Â· vael ostrim" },
  { id: "m5", kind: "image", title: "Iskra's tabard, before", folder: "Character art", uploader: "p4", date: "2026-04-12", tags: ["portrait", "iskra"], placeholder: "portrait Â· iskra vail" },
  { id: "m6", kind: "image", title: "Wakeknight (mask sketch)", folder: "NPC art", uploader: "gm", date: "2026-04-30", tags: ["npc", "mask"], placeholder: "sketch Â· wakeknight mask" },
  { id: "m7", kind: "doc", title: "Drawsteel Backer Packet v0.7", folder: "Rules", uploader: "gm", date: "2026-01-08", tags: ["rules", "pdf"], size: "14.2 MB", ext: "pdf" },
  { id: "m8", kind: "doc", title: "House Rules â€” The Respite", folder: "Rules", uploader: "gm", date: "2026-02-01", tags: ["rules", "house"], size: "84 KB", ext: "md" },
  { id: "m9", kind: "doc", title: "Cinderwake ledger (fragment)", folder: "Handouts", uploader: "gm", date: "2026-04-25", tags: ["handout", "lore"], size: "1.1 MB", ext: "pdf" },
  { id: "m10", kind: "link", title: "Drawsteel official", folder: "References", uploader: "gm", date: "2026-01-08", tags: ["link", "rules"], url: "mcdmproductions.com" },
  { id: "m11", kind: "link", title: "MCDM combat ambient (YT)", folder: "References", uploader: "p2", date: "2026-03-04", tags: ["link", "audio"], url: "youtube.com/..." },
  { id: "m12", kind: "link", title: "Tactical map tool", folder: "References", uploader: "gm", date: "2026-02-22", tags: ["link", "tool"], url: "owlbear.rodeo" },
];

const NOTES = [
  {
    id: "n1",
    authorId: "gm",
    sessionId: "s14",
    posted: "2026-05-02T22:14:00",
    body: "Reminder for Saturday â€” we left off at the lip of the well. If you want to do any prep (potions, rites, info-gathering in town), DM me before Friday and we'll resolve it offline.",
    tags: ["prep"],
  },
  {
    id: "n2",
    authorId: "p2",
    sessionId: "s13",
    posted: "2026-04-26T01:08:00",
    body: "I've been thinking about the ferryman. He took 'Halvern' from me. I'm starting to think that wasn't a substitution â€” I think the ferryman knows who Halvern is, and he just collected on a different debt. We need to find out what Halvern owed.",
    tags: ["theory", "ferryman"],
  },
  {
    id: "n3",
    authorId: "p4",
    sessionId: "s12",
    posted: "2026-04-12T11:42:00",
    body: "I'm not going to be able to play this Saturday well if we just pick up. Can we open with five minutes of Iskra writing the names of the dead? I don't need it to be mechanical, just â€” a moment. Thanks.",
    tags: ["request", "tone"],
  },
  {
    id: "n4",
    authorId: "p1",
    sessionId: "s13",
    posted: "2026-04-26T00:55:00",
    body: "If anyone is keeping a count: the bell rang twice this session. Once when we crossed water, once when Vael read the page. I think it rings when something becomes irrevocable.",
    tags: ["lore", "bell"],
  },
  {
    id: "n5",
    authorId: "p3",
    sessionId: "s13",
    posted: "2026-04-26T09:12:00",
    body: "Bringing a stew. Iskra please eat this time. Bramble will not stop nagging until you do.",
    tags: ["snacks"],
  },
  {
    id: "n6",
    authorId: "gm",
    sessionId: "s11",
    posted: "2026-03-29T20:01:00",
    body: "Updated the Cinderwake page in Media â†’ Handouts. The ledger fragment Sable lifted has three names redacted. One of them is in the Stillwater Grove records. Bramble â€” when you're ready, ask me about it in-character.",
    tags: ["gm-note", "thread"],
  },
  {
    id: "n7",
    authorId: "p2",
    sessionId: null,
    posted: "2026-04-29T18:30:00",
    body: "Tiny rules thing â€” I keep forgetting that triggered abilities don't cost an action. Can we agree to call it out when someone burns one so we all stay sharp?",
    tags: ["rules"],
  },
];

const COUNTDOWN_TARGET = SESSIONS.find(s => s.upcoming).date;

Object.assign(window, {
  PLAYERS, CHARACTERS, SESSIONS, MEDIA, NOTES, COUNTDOWN_TARGET,
});

